.TH asciifield 1 "2015-08-13" "asciifield" "User Commands"
.\" --------------------------------------------------------------------
.SH NAME
asciifield \- ASCII starfield
.\" --------------------------------------------------------------------
.SH SYNOPSIS
\fBasciifield\fP
[\fB\-e\fP]
[\fB\-n\fP \fIn\fP]
[\fB\-s\fP \fIn\fP]
[\fB\-f\fP \fIa\fP]
.\" --------------------------------------------------------------------
.SH DESCRIPTION
This program renders a starfield, much like the good old screensaver.
.\" --------------------------------------------------------------------
.SH OPTIONS
.TP
\fB\-e\fP
Draw a little ship.
.TP
\fB\-n\fP \fIn\fP
Draw \fIn\fP stars. Default is \fB300\fP.
.TP
\fB\-s\fP \fIn\fP
Set speed. Default is \fB4\fP.
.TP
\fB\-f\fP \fIa\fP
Set font aspect ratio (width / height). Defaults to \fB0.5\fP.
.\" --------------------------------------------------------------------
.SH LICENSE
\fBasciifield\fP is released as \(lqPIZZA-WARE\(rq. See the accompanying
\fILICENSE\fP file.
.\" --------------------------------------------------------------------
.SH HISTORY
\fBasciifield\fP was originally written by Peter Hofmann. The project
was started in February 2015.
